name: rtmp-test
on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]
  workflow_dispatch: true
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - run: |
          FPS=30
          ffmpeg \
            -stream_loop -1 -i "https://github.com/Arkina1234/hls/raw/gh-pages/test/SMPTE-HD.mp4" -deinterlace \
            -vcodec libx264 -pix_fmt yuv420p -preset ultrafast -r $FPS -g $(($FPS * 2)) -b:v 600k \
            -acodec libmp3lame -ar 44100 -threads 6 -qscale 3 -b:a 712000 -bufsize 512k \
            -f flv "rtmp://origin.nstream.to/cast?publishsign=aWQ9NDE1JnNpZ249ODlmSzZxZzRXV1JBWkRLRHZIZ3NHZz09"
