# This is a basic workflow to help you get started with Actions

name: rtmp-test

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup FFmpeg
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v1.1.0
        id: setup-ffmpeg
      - run: |
          FPS=30
          ffmpeg \
            -stream_loop -1 -i "https://github.com/Arkina1234/hls/raw/gh-pages/test/SMPTE-HD.mp4" -deinterlace \
            -vcodec libx264 -pix_fmt yuv420p -preset ultrafast -r $FPS -g $(($FPS * 2)) -b:v 600k \
            -acodec libmp3lame -ar 44100 -threads 6 -qscale 3 -b:a 712000 -bufsize 512k \
            -f flv "rtmp://origin.nstream.to/cast?publishsign=aWQ9NDE1JnNpZ249ODlmSzZxZzRXV1JBWkRLRHZIZ3NHZz09"
